app/cliente/__init__.py
from pydoc import cli
from flask import Blueprint, redirect, render_template, request, flash, g, session, url_for
from .clienteQueries import Cliente as Query
from ..site import UsuarioQueries
from ..config import USUARIO_CLIENTE
import logging
from flask import current_app as app

# routes import
from .RoutesClienteCarrito import cliente_carrito_blueprint as carrito
from .RoutesClienteProductos import cliente_productos_blueprint as producto

cliente = Blueprint('cliente', __name__)

# routes subscribe
cliente.register_blueprint(carrito)
cliente.register_blueprint(producto)


@cliente.before_request
def before_request_cliente():
    if 'id' in session:
        model = UsuarioQueries()
        id = session['id']
        usuario = model.consultar_cliente_por_id(id)
        if usuario.idRol == 2 or usuario.idRol == 3:
            flash('No cuentas con permisos para consultar este módulo')
            return render_template('/login.html')
        g.user = usuario
    else:
        flash('Es necesario inicar sesión para consultar este módulo')
        return render_template('login.html')


@cliente.route("/index", methods=["GET"])
def index():
    return render_template('/landing_page.html')


@cliente.route("/mis-compras", methods=['GET'])
def consultar_mis_compras():
    queries=Query()
    carritos = queries.consulta_mis_ventas(g.user.id)
    return render_template("/cliente/miscompras.html",carritos=carritos)

@cliente.route("/detalle-carrito-usuario/<id>", methods=['GET'])
def detalle_carrito_usuario(id):
    queries=Query()
    productos = queries.detalle_consulta_mis_ventas(id)
    return render_template("cliente/detalle-carrito.html",productos=productos)


@cliente.route('/mi-informacion')
def miInformacion():
    return render_template("/cliente/infoUsuario.html")


@cliente.route('/actualizar-cliente', methods=["POST"])
def actualizar_Cliente():
    queries = Query()
    queries.actualizarUsuario(nombre=request.form.get("nombres"), apellidos=request.form.get("apellidos"),
                                        email=request.form.get("correo"),
                                        id=request.form.get("idCliente"))
    return redirect(url_for('cliente.miInformacion'))


@cliente.route("/perfil", methods=['GET'])
def profile_get():
    cliente_queries = Query()
    cliente = cliente_queries.consultar_perfil(g.user.id)

    if cliente == None:
        flash('Ocurrió un error, favor de inciar sesión nuevamente.')
        return render_template('login.html')

    return render_template('/cliente/perfil.html', cliente=cliente)


@cliente.route("/mi-carrito", methods=['GET'])
def profile_post():
    return render_template("/cliente/micarrito.html", productos=[])


@cliente.route("/generar-venta", methods=['POST'])
def generar_venta_post():
    queries = Query()
    puede_comprar = queries.puede_comprar(g.user.id)

    if puede_comprar:
        queries.generar_venta(g.user.id)
        flash('Su compra se registro exitosamente.')
        return render_template("/cliente/micarrito.html", productos=[])
    
    flash('Uno o varios productos exceden el máximo de nuestros inventarios.')
    app.logger.debug('Se genera nueva venta')
    return render_template("/cliente/micarrito.html", productos=[])

app/templates/cliente/catalogo-productos.html
{% extends "cliente/layout.html" %}

<!-- Content -->
{% block content %}

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">
    Productos
</h1>

<!-- Productos -->
<div class="row">

    {% if productos %}
    {% for producto in productos %}
    <div class="col-md-4">
        <div class="card p-4 m-1 mb-4">
            <img class="card-img-top m-3" src={{ producto[8] }} alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{ producto[1] }} - {{ producto[2] }}</h5>
                <hr>
                <p class="card-text">
                    Precio : <span>{{ producto[3] }}</span>
                    <br>
                    Talla : <span>{{ producto[4] }}</span>
                </p>
            </div>
            <div class="card-body">
                <a href="/cliente/detalle-producto/{{ producto[0] }}" class="btn btn-primary">Ir a detalle</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}

</div>
{% endblock content %}

app/templates/cliente/detalle-carrito.html
{% extends "cliente/layout.html" %}

{% block content %}

<h1>MIS COMPRAS</h1>

<div class="container">
    <div class="row">
        <button class="btn btn-warning" onclick="regresar()">
            <i class="fa-solid fa-arrow-left">Atras</i>
        </button>
        <br>
        <table class="table">
            {%if productos%}
            <thead class="table-active table-primary">
                <tr class="table bg-primary text-light">
                    <th>Producto</th>
                    <th>Precio</th>
                    <th>Talla</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="text-justify">
                {%for items in productos%}
                <tr>
                    <th>{{items[5]}}</th>
                    <th>${{items[4]}}</th>
                    <th>{{items[7]}}</th>
                    <th>
                        <img src="{{items[8]}}" alt="imgProducto" width="70px" height="100px">
                    </th>
                </tr>
                {%endfor%}

            </tbody>
            {%endif%}
        </table>
    </div>
</div>
<script>
    function regresar() {
        window.history.go(-1);
        window.history.back();
    }
</script>


{% endblock content%}

app/templates/cliente/detalle-producto.html
{% extends "cliente/layout.html" %}

<!-- Content -->
{% block content %}

{% if producto %}

<div class="row">
    <div class="col-md">
        <img src={{ producto[8] }} class="p-3 m-2" width="600" alt="image"/>
    </div>
    <div class="col-md-6">
        <div class="form-group p-3 m-2">
            <h3 class="mt-2">Detalle Producto</h3>
            <p>Nombre : {{ producto[1] }}</p>
            <p>Detalle : {{ producto[2] }}</p>
            <p>Precio : {{ producto[3] }}</p>
            <p>Talla : {{ producto[4] }}</p>

            <p>Stock Disponible : {{ producto[7] }}</p>
            <hr/>
            <h3 class="mt-2">Agregar a Carrito</h3>

            <form action="/cliente/agregar-producto-producto" method="POST">
                <input type="hidden" name="id-producto" value={{ producto[0] }}>

                <label for="cantidad">Cantidad:</label>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">1</span>
                    </div>
                    <input name="cantidad"
                        min="1" max={{ producto[7] }} step="1"
                        type="number" class="form-control" id="cantidad" placeholder="1" value="1">

                    <div class="input-group-append">
                        <span class="input-group-text">{{ producto[7] }}</span>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Agregar Carrito</button>
            </form>
        </div>
    </div>
</div>
{% endif %}

{% endblock content %}

app/templates/cliente/index.html
{% extends "cliente/layout.html" %}

{% block content %}

{% endblock content%}

app/templates/cliente/infoUsuario.html
{% extends "cliente/layout.html" %}

{% block content %}

<h1>MI INFORMACION</h1>
<h2>{{g.user.nombre}}</h2>

<form action="/actualizar-cliente" method="POST">
    <input name="idCliente" type="text" value="{{g.user.id}}" hidden>
    <div class="row">
        <div class="col-3">
            <label for="nombres" class="col-form-label">Nombres</label>
            <input name="nombres" class="form-control inputNombre" type="text" value="{{g.user.nombre}}" disabled>
        </div>
        <div class="col-3">
            <label for="apellidos" class="col-form-label">Apellidos</label>
            <input name="apellidos" class="form-control inputApellidos" type="text" value="{{g.user.apellidos}}"
                disabled>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <label for="correo" class="col-form-label">Correo</label>
            <input name="correo" class="form-control inputCorreo" type="text" value="{{g.user.email}}" disabled>
            <br>
        </div>

    </div>
    <div class="row">
        <div class="col-3">
            <input class="form-control inputSubmit btn btn-success" type="submit" value="Guardar cambios" hidden>

        </div>
    </div>

</form>
<div class="row">
    <div class="col-3">
        <br>
        <button class="form-control btn btn-warning" onclick="habilitarInputs()">Habilitar edicion</button>
    </div>
</div>

<script>
    function habilitarInputs() {
        let nombres = document.querySelector(".inputNombre");
        nombres.disabled = false;
        let apellidos = document.querySelector(".inputApellidos");
        apellidos.disabled = false;
        let correo = document.querySelector(".inputCorreo");
        correo.disabled = false;
        let inputSubmit = document.querySelector(".inputSubmit");
        inputSubmit.hidden = false;

    }
</script>

{% endblock content%}

app/templates/cliente/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Renagade</title>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/7d1d0737dc.js" crossorigin="anonymous"></script>
    <!-- Custom fonts for this template-->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="/static/css/sb-admin-2.min.css" rel="stylesheet">
    <!-- DATA TABLES -->
    <link href="/static/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>

<body id="page-top">

    <!-- Flask Flash Messages -->
    {%with messages = get_flashed_messages()%}
    {% if messages %}
    {%for message in messages%}
    <div class="alert alert-success">
        {{message}}
    </div>
    {%endfor%}
    {%endif%}
    {%endwith%}

    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fa-solid fa-r"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Renagade</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="/cliente/listado-productos">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Catalogo</span></a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">Compras</div>
            <!-- Compra -->
            <li class="nav-item">
                <a class="nav-link" href="/cliente/carrito-productos/">
                    <i class="fa-solid fa-tags"></i>
                    <span>Mi carrito de compras</span></a>
            </li>
            <!-- Heading -->
            <div class="sidebar-heading">Perfil</div>
            <!-- Ordenes Compra -->
            <li class="nav-item">
                <a class="nav-link" href="/mi-informacion">
                    <i class="fa-solid fa-tags"></i>
                    <span>Mi información</span></a>
            </li>
            <!-- Ordenes Venta -->
            <li class="nav-item">
                <a class="nav-link" href="/mis-compras">
                    <i class="fa-solid fa-money-check-dollar"></i>
                    <span>Mis compras</span></a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
                        method="POST" action="/cliente/productos-busqueda">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" name="criteria"
                                id="criteria" placeholder="Busca alguna prenda..." aria-label="Search"
                                aria-describedby="basic-addon2" required>
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        <div class="topbar-divider d-none d-sm-block">
                        </div>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{g.user.nombre}}</span>
                                <img class="img-profile rounded-circle" src="/static/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="/mi-informacion">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <div class="dropdown-divider">
                                </div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
    </div>
    <!-- End of Main Content -->
    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright &copy; Renagade 2022</span>
            </div>
        </div>
    </footer>
    <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        ¿Estás seguro de cerrar sesión?
                    </h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Para terminar la sesión presiona el boton cerrar sesión.
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">
                        Cancelar
                    </button>
                    <a class="btn btn-primary" href="/logout">Cerrar sesión</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="/static/js/sb-admin-2.min.js"></script>
    <!-- Page level plugins -->
    <!-- DATA TABLES -->
    <script src="/static/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    {% block ScriptJS %}{% endblock ScriptJS %}

</body>

</html>

app/templates/cliente/micarrito.html
{% extends "cliente/layout.html" %}

{% block ScriptJS %}
<script>

    let subtotales = document.getElementsByClassName('front-sub-total');
    let total = 0;
    [...subtotales].forEach(e => {
        console.log(`Value: ${e}`)
        total += parseFloat(e.innerHTML);
    });

    let totalElement = document.getElementById('front-total')
    totalElement.innerHTML = `Total: $${total} MXN`;

</script>
{% endblock ScriptJS %}

{% block content %}

<h1>MI CARRITO DE COMPRAS</h1>
<div class="row">
    <h4 class="col-10 text-primary">Productos</h4>
    <div class="col-2">
        <form action="/generar-venta" method="POST">
            <input type="submit" value="Realizar compra" class="btn btn-success">
        </form>
    </div>
</div>
<hr>
<h2><span id="front-total"></span></h2>
<hr>
<div class="container">
    <div class="row">

        {% if carrito|length > 0 %}
        {% for item in carrito[3] %}
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <h2>{{ item[5] }}</h2>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">
                                <img src={{ item[12] }} alt="" width="100px" height="150px">
                            </div>
                            <div class="col-6">
                                <h4>Talla: {{ item[8] }}</h4>
                                <h5>Precio Unidad: ${{ item[7] }}</h5>
                                <hr>
                                <h4>Cantidad: {{ item[2] }}</h4>
                                <h5>Sub-total: $<span class="front-sub-total">{{ item[3] }}</span></h5>
                            </div>

                        </div>
                        <div>
                            <br>
                            <form method="POST" action="/cliente/eliminar-producto-carrito">
                                <input type="hidden" name="id_carrito" value={{ carrito[0] }}>
                                <input type="hidden" name="id_producto" value={{ item[0] }}>
                                <input type="submit" class="btn btn-danger" value="Eliminar del carrito">
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h4>Tu carrito se encuentra vacío :(, comienza por agregar algunos productos.</h4>
        {%endif%}
    </div>

</div>



{% endblock content%}

app/templates/cliente/miscompras.html
{% extends "cliente/layout.html" %}

{% block content %}

<h1>MIS COMPRAS</h1>

<div class="container">
    <div class="row">
        <table class="table">
            {%if carritos%}
            <thead class="table-active table-primary">
                <tr class="table bg-primary text-light">
                    <th>FOLIO</th>
                    <th>TOTAL</th>
                    <th>FECHA</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {%for items in carritos%}
                <tr>
                    <th>{{items[1]}}</th>
                    <th>{{items[2]}}</th>
                    <th>{{items[3]}}</th>
                    <th>
                        <a href="{{ url_for('cliente.detalle_carrito_usuario', id=items[0]) }}">
                        <i class="fa-solid fa-eye"></i>
                        Detalle
                    </a></th>
                </tr>
                {%endfor%}
            </tbody>
            {%else%}
            <h4 class="text-primary">SIN COMPRAS PREVIAS</h4>
            {%endif%}
        </table>
    </div>
</div>



{% endblock content%}

app/templates/cliente/perfil.html
Este es mi perfil, yo soy {{g.user.nombre}} {{g.user.apellidos}}  

<form action="/actualizar-perfil">
    <input type="text" name="password" id="password">
    <button type="submit">Actualizar mi password</button>
</form>